export const homeObjOne = {
    id : 'about',
    lightBg:false,
    lightText : true ,
    lightTextDesc : true ,
    topLine : "premium bank",
    headLine : 'Unlimited Transactions with zero fees',
    describtion :'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    imgStart : false,
    buttonlabel : 'Get started',
    img : require('../../images/svg2.svg'),
    alt:'car',
    dark : true,
    primary:true,
    darkText : false ,
}
export const homeObjTwo = {
    id : 'discover',
    lightBg:true,
    lightText : false ,
    lightTextDesc : false ,
    topLine : "unlimited access",
    headLine : 'Unlimited Transactions with zero fees',
    describtion :'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    imgStart : true,
    buttonlabel : 'learn more',
    img : require('../../images/svg3.svg'),
    alt:'car',
    dark : true,
    primary:false,
    darkText : true ,
}
export const homeObjThree = {
    id : 'signup',
    lightBg:false,
    lightText : true ,
    lightTextDesc : true ,
    topLine : "premium bank",
    headLine : 'Unlimited Transactions with zero fees',
    describtion :'Get access to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    imgStart : false,
    buttonlabel : 'Start Now',
    img : require('../../images/svg1.svg'),
    alt:'car',
    dark : true,
    primary:true,
    darkText : false ,
}